DROP DATABASE IF EXISTS oso;
USE oso;
CREATE TABLE DEVICES (IDDevice INTEGER PRIMARY KEY NOT NULL,
Address VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Description VARCHAR(100),
Location VARCHAR(50));
